[package]
description = "WasmEdge wit-bindgen"
edition = "2021"
license = "Apache-2.0"
name = "wasmedge-wit-bindgen-rust"
readme = "README.md"
version = "0.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
